baseURL = "https://watsup.cs.northwestern.edu/"
languageCode = "en-us"
title = "WatsUp CS"

copyright = "Â© WatsUp CS 2025"

enableEmoji = true

theme = "hugo-bootstrap-theme"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":fileModTime", ":default"]

[params]
github = "https://github.com/nu-cs-students/nu-watsup-cs.github.io/edit/main/content"

# Main menu
[menus]
# [[menus.main]]
# name = 'Home'
# pageRef = '/'
# weight = 10

[[menus.main]]
name = 'Events'
pageRef = '/events'
weight = 20

[[menus.main]]
name = 'Initiatives'
pageRef = '/initiatives'
weight = 30

[[menus.main]]
name = 'Wiki'
pageRef = '/wiki'
weight = 40

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 50

[caches]
[caches.images]
dir = ':cacheDir/images'
